package com.biginsect.signinmanagement.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.biginsect.signinmanagement.dao.Course.DayForWeek;
import com.biginsect.signinmanagement.dao.Course.DayForWeekConverter;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COURSE".
*/
public class CourseDao extends AbstractDao<Course, Long> {

    public static final String TABLENAME = "COURSE";

    /**
     * Properties of entity Course.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CourseId = new Property(0, long.class, "courseId", true, "_id");
        public final static Property CourseName = new Property(1, String.class, "courseName", false, "COURSE_NAME");
        public final static Property DayForWeek = new Property(2, Integer.class, "dayForWeek", false, "DAY_FOR_WEEK");
        public final static Property StartTime = new Property(3, long.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(4, long.class, "endTime", false, "END_TIME");
    }

    private final DayForWeekConverter dayForWeekConverter = new DayForWeekConverter();

    public CourseDao(DaoConfig config) {
        super(config);
    }
    
    public CourseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COURSE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: courseId
                "\"COURSE_NAME\" TEXT," + // 1: courseName
                "\"DAY_FOR_WEEK\" INTEGER," + // 2: dayForWeek
                "\"START_TIME\" INTEGER NOT NULL ," + // 3: startTime
                "\"END_TIME\" INTEGER NOT NULL );"); // 4: endTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COURSE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Course entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCourseId());
 
        String courseName = entity.getCourseName();
        if (courseName != null) {
            stmt.bindString(2, courseName);
        }
 
        DayForWeek dayForWeek = entity.getDayForWeek();
        if (dayForWeek != null) {
            stmt.bindLong(3, dayForWeekConverter.convertToDatabaseValue(dayForWeek));
        }
        stmt.bindLong(4, entity.getStartTime());
        stmt.bindLong(5, entity.getEndTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Course entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCourseId());
 
        String courseName = entity.getCourseName();
        if (courseName != null) {
            stmt.bindString(2, courseName);
        }
 
        DayForWeek dayForWeek = entity.getDayForWeek();
        if (dayForWeek != null) {
            stmt.bindLong(3, dayForWeekConverter.convertToDatabaseValue(dayForWeek));
        }
        stmt.bindLong(4, entity.getStartTime());
        stmt.bindLong(5, entity.getEndTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Course readEntity(Cursor cursor, int offset) {
        Course entity = new Course( //
            cursor.getLong(offset + 0), // courseId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // courseName
            cursor.isNull(offset + 2) ? null : dayForWeekConverter.convertToEntityProperty(cursor.getInt(offset + 2)), // dayForWeek
            cursor.getLong(offset + 3), // startTime
            cursor.getLong(offset + 4) // endTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Course entity, int offset) {
        entity.setCourseId(cursor.getLong(offset + 0));
        entity.setCourseName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDayForWeek(cursor.isNull(offset + 2) ? null : dayForWeekConverter.convertToEntityProperty(cursor.getInt(offset + 2)));
        entity.setStartTime(cursor.getLong(offset + 3));
        entity.setEndTime(cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Course entity, long rowId) {
        entity.setCourseId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Course entity) {
        if(entity != null) {
            return entity.getCourseId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Course entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
