package com.biginsect.signinmanagement.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.biginsect.signinmanagement.dao.Student;
import com.biginsect.signinmanagement.dao.Teacher;
import com.biginsect.signinmanagement.dao.Schedule;

import com.biginsect.signinmanagement.dao.StudentDao;
import com.biginsect.signinmanagement.dao.TeacherDao;
import com.biginsect.signinmanagement.dao.ScheduleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig teacherDaoConfig;
    private final DaoConfig scheduleDaoConfig;

    private final StudentDao studentDao;
    private final TeacherDao teacherDao;
    private final ScheduleDao scheduleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        scheduleDaoConfig = daoConfigMap.get(ScheduleDao.class).clone();
        scheduleDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);
        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(Teacher.class, teacherDao);
        registerDao(Schedule.class, scheduleDao);
    }
    
    public void clear() {
        studentDaoConfig.clearIdentityScope();
        teacherDaoConfig.clearIdentityScope();
        scheduleDaoConfig.clearIdentityScope();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public ScheduleDao getScheduleDao() {
        return scheduleDao;
    }

}
