package com.biginsect.signinmanagement.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.biginsect.signinmanagement.dao.Student;
import com.biginsect.signinmanagement.dao.Teacher;
import com.biginsect.signinmanagement.dao.Schedule;
import com.biginsect.signinmanagement.dao.Attendance;
import com.biginsect.signinmanagement.dao.Course;
import com.biginsect.signinmanagement.dao.Lesson;

import com.biginsect.signinmanagement.dao.StudentDao;
import com.biginsect.signinmanagement.dao.TeacherDao;
import com.biginsect.signinmanagement.dao.ScheduleDao;
import com.biginsect.signinmanagement.dao.AttendanceDao;
import com.biginsect.signinmanagement.dao.CourseDao;
import com.biginsect.signinmanagement.dao.LessonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig teacherDaoConfig;
    private final DaoConfig scheduleDaoConfig;
    private final DaoConfig attendanceDaoConfig;
    private final DaoConfig courseDaoConfig;
    private final DaoConfig lessonDaoConfig;

    private final StudentDao studentDao;
    private final TeacherDao teacherDao;
    private final ScheduleDao scheduleDao;
    private final AttendanceDao attendanceDao;
    private final CourseDao courseDao;
    private final LessonDao lessonDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        scheduleDaoConfig = daoConfigMap.get(ScheduleDao.class).clone();
        scheduleDaoConfig.initIdentityScope(type);

        attendanceDaoConfig = daoConfigMap.get(AttendanceDao.class).clone();
        attendanceDaoConfig.initIdentityScope(type);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        lessonDaoConfig = daoConfigMap.get(LessonDao.class).clone();
        lessonDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);
        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);
        attendanceDao = new AttendanceDao(attendanceDaoConfig, this);
        courseDao = new CourseDao(courseDaoConfig, this);
        lessonDao = new LessonDao(lessonDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(Teacher.class, teacherDao);
        registerDao(Schedule.class, scheduleDao);
        registerDao(Attendance.class, attendanceDao);
        registerDao(Course.class, courseDao);
        registerDao(Lesson.class, lessonDao);
    }
    
    public void clear() {
        studentDaoConfig.clearIdentityScope();
        teacherDaoConfig.clearIdentityScope();
        scheduleDaoConfig.clearIdentityScope();
        attendanceDaoConfig.clearIdentityScope();
        courseDaoConfig.clearIdentityScope();
        lessonDaoConfig.clearIdentityScope();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public ScheduleDao getScheduleDao() {
        return scheduleDao;
    }

    public AttendanceDao getAttendanceDao() {
        return attendanceDao;
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public LessonDao getLessonDao() {
        return lessonDao;
    }

}
